#Switches 
set_property PACKAGE_PIN        V17      [get_ports {sw[0]}]
    set_property IOSTANDARD LVCMOS33     [get_ports {sw[0]}]
set_property PACKAGE_PIN        V16      [get_ports {sw[1]}]
    set_property IOSTANDARD LVCMOS33     [get_ports {sw[1]}]
set_property PACKAGE_PIN        W16      [get_ports {sw[2]}]
    set_property IOSTANDARD LVCMOS33     [get_ports {sw[2]}]
    
#Leds
set_property PACKAGE_PIN        U16      [get_ports {sw[0]}]
    set_property IOSTANDARD LVCMOS33     [get_ports {sw[0]}]
set_property PACKAGE_PIN        E19      [get_ports {sw[1]}]
    set_property IOSTANDARD LVCMOS33     [get_ports {sw[1]}]
set_property PACKAGE_PIN        U19      [get_ports {sw[2]}]
    set_property IOSTANDARD LVCMOS33     [get_ports {sw[2]}]
set_property PACKAGE_PIN        19       [get_ports {sw[3]}]
    set_property IOSTANDARD LVCMOS33     [get_ports {sw[3]}]
set_property PACKAGE_PIN        W18      [get_ports {sw[4]}]
    set_property IOSTANDARD LVCMOS33     [get_ports {sw[4]}]
set_property PACKAGE_PIN        U15      [get_ports {sw[5]}]
    set_property IOSTANDARD LVCMOS33     [get_ports {sw[5]}]
set_property PACKAGE_PIN        U14      [get_ports {sw[6]}]
    set_property IOSTANDARD LVCMOS33     [get_ports {sw[6]}]
set_property PACKAGE_PIN        V14      [get_ports {sw[7]}]
    set_property IOSTANDARD LVCMOS33     [get_ports {sw[7]}]